name: supernodeapp
description: Mobile app used to interact with MXC Supernodes.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+10  

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  flutter_i18n: ^0.13.0
  flutter_local_notifications: ^1.4.1
  flutter_map: any
  flutter_mobx: ^1.1.0
  fluro: ^1.6.2
  fish_redux: ^0.3.1
  latlong: ^0.6.1
  majascan: ^0.3.7
  mobx: ^1.1.1
  mobx_codegen: ^1.0.3
  pin_code_fields: ^2.4.0
  permission_handler: ^4.2.0
  sqflite: ^1.3.0
  supernova_flutter_ui_toolkit: ^0.0.2
  qr_flutter: ^3.2.0
  url_launcher: ^5.4.5
#  user_location: any
  toast: ^0.1.5
  flutter_spinkit: "^2.1.0"
  localstorage: ^3.0.0
  shared_preferences: ^0.5.6+3
  flutter_bugly: ^0.2.8
  page_transition: ^1.1.5
  local_auth: 0.6.2+3
  location: ^3.0.0

#  open_file:

dev_dependencies:
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flutter_i18n/
    # - assets/flutter_i18n/en/
    # - assets/flutter_i18n/zh_CN/
    # - assets/flutter_i18n/zh_TW/
    # - assets/flutter_i18n/ko/
    # - assets/flutter_i18n/ja/
    - assets/images/app/
    - assets/images/login/
    - assets/images/splash/
    - assets/images/home/
    - assets/images/deposit/
    - assets/images/withdraw/
    - assets/images/stake/
    - assets/others/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: .SF NS Display
      fonts:
        - asset: assets/fonts/SFNSDisplay.ttf
    - family: .SF NS Text
      fonts:
        - asset: assets/fonts/SFNSText.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
